services:
  - type: web
    name: localconnect
    runtime: python
    plan: free
    region: singapore
    rootDir: localconnect-source-code
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOW_DEMO_PAYMENTS
        value: "true"
      - key: STRIPE_CURRENCY
        value: inr
